os: osx
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_install:
- brew update && brew install git-lfs
- git lfs install
install:
- npm install
before_script:
- git lfs pull
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: Gw/JyG+M/dUxgI9UXxoY/sAAogE3uQYCZvZjVON+y+YZ9ntJlK4u6u5RQJxPIRr+fek0hpnxq3AtVJoajKJvsZ3cTvZ1S7TImUjOxl13/2PrW79rSlzV5YHMfDD2yF0UllCxQ4l5/R1ZqBT5RgI2VVtDES2B2Qo+9xSr62wpttUjBElyeyaZTmsUvS3qlXr5IHnbbFsOJhTZvT1/c/7pI9ZAXuvhJRvaS+ki2b0TLIez+TsEPToDimT28T+fqLYN4FCNkndREBVMqpNVe5cmGMR7xW8Eru17w+WPjLH/TrmtqY4QK/i5Epboq/tp1WSH/d5ZH50rvAZJ8alEJf8j2DmnvtG5DqvYGuuKkbzLhb2b6Rp2WXOn/igG1CIKGRHXJP+PRlApkrs6hOMY2N8yDwW0VpGXr1IOhlJkDRabU54LhjOBEiAACACfWxsxJne9q1H75yM5LMsqNij3ZBCBONTQho7weZKtuXRps6iRY6Dmj5ezJEu0ybKqA+YRwPkyWsdlfc/PoJiktpusQtPvpO+SLht7iAQCkljJ/BHI7csI90vLDz3DIwqOuP+qw+yLFsm+x/Z3+6mkkAHOfsJ57uf6ypphaG221mxzAWlqphCyCtfQPjtlnBMb8Nf4AzuGGkAU5Rcjnrs3rWUlor1sDoERcQAF38ba7nGpURvqDzQ=
  file: fauxtiverb.zip
  skip_cleanup: true
  on:
    repo: delucis/fauxtiverb
    tags: true
